# Generated by Django 5.1.3 on 2024-11-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='total_votes',
            new_name='votes',
        ),
    ]
